// Code generated by mockery v2.37.0. DO NOT EDIT.

package mocks

import (
	http "net/http"
	url "net/url"

	mock "github.com/stretchr/testify/mock"
)

// HTTPClientInterface is an autogenerated mock type for the HTTPClientInterface type
type HTTPClientInterface struct {
	mock.Mock
}

// PostForm provides a mock function with given fields: _a0, data
func (_m *HTTPClientInterface) PostForm(_a0 string, data url.Values) (*http.Response, error) {
	ret := _m.Called(_a0, data)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string, url.Values) (*http.Response, error)); ok {
		return rf(_a0, data)
	}
	if rf, ok := ret.Get(0).(func(string, url.Values) *http.Response); ok {
		r0 = rf(_a0, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string, url.Values) error); ok {
		r1 = rf(_a0, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHTTPClientInterface creates a new instance of HTTPClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPClientInterface {
	mock := &HTTPClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
